#%RAML 0.8
title: siva-ABCcafe
version: 1.0
baseUri: http://localhost:8081/api
/insertintoBillto:
  
  get:
    description: inserting data into Billto
/insertintosell :
  
   get:
    description: inserting data into Sellto
/insertoMachine:
  get:
    description: inserting data into machine